### ISSUE TITLE
I am running this code in python3.7

### ISSUE THREAD

**Issue by 343695222** [jacquelinelala/GFN#18]
Traceback (most recent call last):
  File "test_GFN_4x.py", line 131, in <module>
    model_test(model)
  File "test_GFN_4x.py", line 101, in model_test
    test(testloader, model, criterion, SR_dir)
  File "test_GFN_4x.py", line 91, in test
    print("Avg. SR PSNR:{:4f} dB".format(avg_psnr / iteration))
UnboundLocalError: local variable 'iteration' referenced before assignment

**Comment by 343695222** [comment]
Testing on the given 3-step trained model which stores in /models, and ends with pkl.
Testing model is GFN_epoch_55.pkl----------------------------------
D:\Anaconda3\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\Anaconda3\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\Anaconda3\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.activation.LeakyReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\Anaconda3\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\Anaconda3\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\Anaconda3\lib\site-packages\torch\serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.pixelshuffle.PixelShuffle' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\Anaconda3\lib\site-packages\torch\nn\_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
Namespace(dataset='C:\\Users\\陈东祥\\Desktop\\GFN\\GFN\\GOPRO_Large\\Validation_4x', gated=True, intermediate_process='', isTest=True, scale=4)
Traceback (most recent call last):
  File "test_GFN_4x.py", line 131, in <module>
    model_test(model)
  File "test_GFN_4x.py", line 101, in model_test
    test(testloader, model, criterion, SR_dir)
  File "test_GFN_4x.py", line 91, in test
    print("Avg. SR PSNR:{:4f} dB".format(avg_psnr / iteration))
UnboundLocalError: local variable 'iteration' referenced before assignment
