### ISSUE TITLE
gopro_val_generator.m

### ISSUE THREAD

**Issue by zhLawliet** [jacquelinelala/GFN#3]
hi ,why there is no gopro_val_generator.m?

**Comment by zhLawliet** [comment]
I cannot start Test the model on my machine (windows 10, i7 CPU with 16 GB memory),intel.
the error is below,when i run the GFN/test_GFN_x4.py
May you can help me,thanks

Traceback (most recent call last):
  File "F:/11deblur_defocus/GFN/test_GFN_x4.py", line 89, n <module>
    test(testloader, model, criterion, SR_dir)
  File "F:/11deblur_defocus/GFN/test_GFN_x4.py", line 43, in test
    [lr_deblur, scoremap, sr] = model(LR_Blur)
  File "E:\Anaconda3\envs\pytorch36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\11deblur_defocus\GFN\networks\GFN_x4.py", line 186, in forward
    sr = self.conv_output(out)
  File "E:\Anaconda3\envs\pytorch36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda3\envs\pytorch36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "E:\Anaconda3\envs\pytorch36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda3\envs\pytorch36\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: $ Torch: not enough memory: you tried to allocate 31GB. Buy new RAM! at ..\src\TH\THGeneral.c:218

**Comment by jacquelinelala** [comment]
The new version is being modified. Please wait for a few days. If you want
to get any change, please star our project. Thanks for your attention.

**Comment by jacquelinelala** [comment]
The new version is released. Please update the repository and follow the newest README.
